### clear mail
DELETE http://localhost:3333/api/dev/clear/admin@gmail.com


### reg
POST http://localhost:3333/api/register 
content-type: application/json

{
   "email": "admin@gmail.com",
   "password": "VeryStrongPassword"
}

### confirm
GET http://localhost:3333/api/confirm/P9TKdbOlNGiSO7OsEdcflNvWKgfNJC12n1jgMsJEE7A





### login
POST http://localhost:3333/api/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123"
}









### 2. Регистрируем (теперь email точно свободен)
# @name signup
POST http://localhost:3333/api/register
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123"
}

###

### 3. Подтверждаем (переменная подхватится автоматом)
@token = {{signup.response.body.confirm}}

GET http://localhost:3333/api/confirm/{{token}}


### jwt test
GET http://localhost:3333/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3NzMyOTUzMTksImV4cCI6MTc3MzI5NjIxOX0.kG3NijcPd_qSofSGy6FPY-IxP9xw6aGAS7rEBrOXDSI